# Generated by Django 4.1 on 2022-09-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationResourceMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllocationID', models.CharField(db_index=True, max_length=32)),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfScience',
            fields=[
                ('field_of_science_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent_field_of_science_id', models.IntegerField(blank=True, null=True)),
                ('field_of_science_desc', models.CharField(max_length=200)),
                ('fos_nsf_id', models.IntegerField(blank=True, null=True)),
                ('fos_nsf_abbrev', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_localid', models.IntegerField(primary_key=True, serialize=False)),
                ('access_id', models.CharField(db_index=True, max_length=30)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=60, null=True)),
                ('is_suspended', models.BooleanField()),
                ('organization', models.CharField(max_length=300)),
                ('citizenships', models.CharField(max_length=300, null=True)),
                ('emails', models.CharField(max_length=300, null=True)),
                ('addressesJSON', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('ResourceID', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('SiteID', models.CharField(db_index=True, max_length=40)),
                ('OrganizationAbbrev', models.CharField(db_index=True, max_length=40)),
                ('OrganizationName', models.CharField(db_index=True, max_length=120)),
                ('AmieName', models.CharField(db_index=True, max_length=40)),
                ('PopsName', models.CharField(db_index=True, max_length=120)),
                ('TgcdbResourceName', models.CharField(db_index=True, max_length=40)),
                ('ResourceCode', models.CharField(db_index=True, max_length=40)),
                ('ResourceDescription', models.CharField(db_index=True, max_length=40)),
                ('Timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonLocalUsernameMap',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('person_localid', models.IntegerField()),
                ('access_id', models.CharField(db_index=True, max_length=30)),
                ('resource_id', models.IntegerField()),
                ('resource_name', models.CharField(max_length=200)),
                ('resource_username', models.CharField(max_length=30)),
                ('ResourceID', models.CharField(max_length=40)),
            ],
            options={
                'unique_together': {('resource_id', 'resource_username')},
            },
        ),
    ]
