# Generated by Django 4.1.12 on 2024-04-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0002_fieldofscience_fos_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldofscience',
            old_name='nsf_directorage_abbrev',
            new_name='nsf_directorate_abbrev',
        ),
        migrations.RenameField(
            model_name='fieldofscience',
            old_name='nsf_directorage_name',
            new_name='nsf_directorate_name',
        ),
    ]
