version: '1.0'
services :
  db:
    image: postgres:14-bookworm
    ports:
      - "5432:5432"
    environment:
      #POSTGRES_USER: opsdba
      #POSTGRES_PASSWORD: <PASSWORD>
      #POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /pg-data
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - ${POSTGRES_PORT}:8080
    volumes:
      - ./data/db:/pg-data
