version: '2.2'
services :
  db:
    image: postgres:14-bookworm
    container_name: warehouse_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /pg-data
    user: "${UID:?You must do 'export UID' to launch}:${GID:?You must do 'export GID' to launch}"
    volumes:
      - ./dbrestore:/opt/app/dbrestore
      - ./data/db:/pg-data
  django:
    tty: true
    image: warehouse:latest
    container_name: warehouse_django
    restart: always
    depends_on: 
      - db
    ports:
      - "8000:8000"
    environment:
      AWS_SHARED_CREDENTIALS_FILE: /opt/app/aws_credentials_local
    volumes:
      - ../../:/soft/warehouse-2.0/PROD
      - ./DEV/logs:/soft/warehouse-2.0/var/
      - ./dbrestore:/opt/app/dbrestore
      - ${PWD}/aws_credentials:/opt/app/aws_credentials
      - ${HOME}/django_aws_credential_key:/opt/app/django_aws_credential_key
