# Generated by Django 4.1 on 2022-09-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CiderInfrastructure',
            fields=[
                ('cider_resource_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cider_type', models.CharField(max_length=16)),
                ('info_resourceid', models.CharField(db_index=True, max_length=40)),
                ('info_siteid', models.CharField(db_index=True, max_length=40)),
                ('resource_descriptive_name', models.CharField(max_length=120)),
                ('resource_description', models.CharField(max_length=4000, null=True)),
                ('resource_status', models.JSONField()),
                ('current_statuses', models.CharField(max_length=64)),
                ('latest_status', models.CharField(max_length=32, null=True)),
                ('latest_status_begin', models.DateField(null=True)),
                ('latest_status_end', models.DateField(null=True)),
                ('parent_resource', models.IntegerField(db_index=True, null=True)),
                ('recommended_use', models.CharField(max_length=4000, null=True)),
                ('access_description', models.CharField(max_length=4000, null=True)),
                ('project_affiliation', models.CharField(max_length=16, null=True)),
                ('provider_level', models.CharField(max_length=16, null=True)),
                ('other_attributes', models.JSONField()),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
