# Generated by Django 4.1.4 on 2022-12-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciderinfrastructure',
            name='project_affiliation',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
