# Generated by Django 4.1.13 on 2024-11-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cider', '0002_alter_ciderinfrastructure_project_affiliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiderFeatures',
            fields=[
                ('feature_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feature_category_name', models.CharField(max_length=120)),
                ('feature_category_description', models.CharField(max_length=4000, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('other_attributes', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CiderGroups',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('info_groupid', models.CharField(db_index=True, max_length=40)),
                ('group_descriptive_name', models.CharField(max_length=120)),
                ('group_description', models.CharField(max_length=4000, null=True)),
                ('group_logo_url', models.CharField(blank=True, max_length=320, null=True)),
                ('group_types', models.JSONField(blank=True, null=True)),
                ('info_resourceids', models.JSONField(blank=True, null=True)),
                ('other_attributes', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
