# Generated by Django 4.1.13 on 2024-10-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cider', '0002_alter_ciderinfrastructure_project_affiliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiderGroups',
            fields=[
                ('info_groupid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('group_descriptive_name', models.CharField(max_length=120)),
                ('group_description', models.CharField(max_length=4000, null=True)),
                ('group_logo_url', models.CharField(blank=True, max_length=320, null=True)),
                ('group_types', models.JSONField(blank=True, null=True)),
                ('info_resourceids', models.JSONField(blank=True, null=True)),
                ('other_attributes', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
