# Generated by Django 4.1.13 on 2024-10-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cider', '0003_cidergroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiderFeatures',
            fields=[
                ('feature_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feature_category_name', models.CharField(max_length=120)),
                ('feature_category_description', models.CharField(max_length=4000, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('other_attributes', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
