# Generated by Django 4.1.13 on 2024-11-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cider', '0003_ciderfeatures_cidergroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiderOrganizations',
            fields=[
                ('organization_id', models.IntegerField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=120)),
                ('organization_abbrev', models.CharField(max_length=20)),
                ('organization_url', models.CharField(blank=True, max_length=320, null=True)),
                ('other_attributes', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
