# Generated by Django 4.1.13 on 2024-12-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cider', '0004_ciderorganizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciderinfrastructure',
            name='protected_attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ciderinfrastructure',
            name='other_attributes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
