# Generated by Django 5.0.14 on 2025-06-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cider', '0005_ciderinfrastructure_protected_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciderfeatures',
            name='feature_category_types',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
