# Generated by Django 4.1.5 on 2023-09-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_v3', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceV3',
        ),
        migrations.DeleteModel(
            name='ResourceV3Catalog',
        ),
        migrations.DeleteModel(
            name='ResourceV3Local',
        ),
        migrations.DeleteModel(
            name='ResourceV3Relation',
        ),
    ]
