# Generated by Django 5.2.9 on 2026-07-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_state', '0002_alter_publisherinfo_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricAggregation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('About', models.CharField(db_index=True, max_length=255)),
                ('MetricName', models.CharField(db_index=True, max_length=32)),
                ('AggregationType', models.CharField(default='Day', max_length=8)),
                ('AggregationDate', models.DateField(db_index=True)),
                ('MetricCount', models.IntegerField()),
                ('MetricValueSum', models.IntegerField()),
                ('MetricMinValue', models.IntegerField()),
                ('MetricAvgValue', models.FloatField()),
                ('MetricMaxValue', models.IntegerField()),
                ('ErrorCount', models.IntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('About', 'MetricName', 'AggregationType', 'AggregationDate'), name='unique_metric_aggregation')],
            },
        ),
        migrations.CreateModel(
            name='ProcessingMetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ProcessingID', models.CharField(db_index=True, max_length=255)),
                ('ProcessingTimestamp', models.DateTimeField(db_index=True)),
                ('ProcessingError', models.CharField(max_length=64, null=True)),
                ('About', models.CharField(db_index=True, max_length=255)),
                ('MetricName', models.CharField(db_index=True, max_length=32)),
                ('MetricValue', models.IntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ProcessingID', 'ProcessingTimestamp', 'About', 'MetricName'), name='unique_processing_metric')],
            },
        ),
    ]
