# Generated by Django 4.1 on 2022-09-05 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractService',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
                ('ServiceType', models.CharField(max_length=32)),
                ('Type', models.CharField(max_length=32)),
                ('QualityLevel', models.CharField(max_length=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcceleratorEnvironment',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
                ('Type', models.CharField(max_length=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('Scheme', models.CharField(max_length=64, null=True)),
                ('Rule', models.CharField(max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminDomain',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('Description', models.CharField(max_length=128, null=True)),
                ('WWW', models.URLField(null=True)),
                ('Distributed', models.BooleanField(null=True)),
                ('Owner', models.CharField(max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationEnvironment',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
                ('Description', models.CharField(max_length=512, null=True)),
                ('AppName', models.CharField(max_length=64)),
                ('AppVersion', models.CharField(default='none', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComputingActivity',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
                ('LocalOwner', models.CharField(db_index=True, default='unknown', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComputingManager',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComputingManagerAcceleratorInfo',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComputingQueue',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComputingShare',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComputingShareAcceleratorInfo',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('Detail', models.CharField(max_length=128)),
                ('Type', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityHistory',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DocumentType', models.CharField(db_index=True, max_length=32)),
                ('ResourceID', models.CharField(db_index=True, max_length=40, null=True)),
                ('ReceivedTime', models.DateTimeField()),
                ('EntityJSON', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionEnvironment',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDomain',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('Description', models.CharField(max_length=128, null=True)),
                ('WWW', models.URLField(null=True)),
                ('Level', models.IntegerField(null=True)),
                ('UserManager', models.CharField(max_length=200, null=True)),
                ('Member', models.CharField(max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
                ('HealthState', models.CharField(max_length=16)),
                ('ServingState', models.CharField(max_length=16)),
                ('URL', models.CharField(max_length=320)),
                ('QualityLevel', models.CharField(max_length=16, null=True)),
                ('InterfaceVersion', models.CharField(max_length=16)),
                ('InterfaceName', models.CharField(max_length=32)),
                ('AbstractService', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='glue2.abstractservice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationHandle',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', models.JSONField()),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
                ('Type', models.CharField(max_length=16)),
                ('Value', models.CharField(max_length=64)),
                ('ApplicationEnvironment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationhandles', to='glue2.applicationenvironment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
