# Generated by Django 4.1.5 on 2023-07-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glue2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationhandle',
            name='Value',
            field=models.CharField(max_length=80),
        ),
    ]
