# Generated by Django 4.1.13 on 2024-06-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cider', '0002_alter_ciderinfrastructure_project_affiliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration_Badge',
            fields=[
                ('badge_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('graphic', models.ImageField(null=True, upload_to='')),
                ('researcher_summary', models.TextField(null=True)),
                ('resource_provider_summary', models.TextField(null=True)),
                ('verification_summary', models.TextField(null=True)),
                ('verification_method', models.CharField(max_length=20)),
                ('default_badge_access_url', models.URLField()),
                ('default_badge_access_url_label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Integration_Roadmap',
            fields=[
                ('roadmap_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('graphic', models.ImageField(upload_to='')),
                ('executive_summary', models.TextField(null=True)),
                ('infrastructure_types', models.CharField(max_length=200)),
                ('integration_coordinators', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Integration_Roadmap_Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('technical_summary', models.TextField(null=True)),
                ('implementor_roles', models.CharField(max_length=200)),
                ('task_experts', models.CharField(max_length=200)),
                ('detailed_instructions_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Integration_Roadmap_Badge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_no', models.IntegerField()),
                ('required', models.BooleanField(max_length=20)),
                ('badge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_set', related_query_name='roadmap', to='integration_badges.integration_badge')),
                ('roadmap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_set', related_query_name='badge_ref', to='integration_badges.integration_roadmap')),
            ],
            options={
                'unique_together': {('roadmap_id', 'badge_id')},
            },
        ),
        migrations.CreateModel(
            name='Integration_Resource_Roadmap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cider.ciderinfrastructure')),
                ('roadmap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration_badges.integration_roadmap')),
            ],
            options={
                'unique_together': {('resource_id', 'roadmap_id')},
            },
        ),
        migrations.CreateModel(
            name='Integration_Resource_Badge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('badge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration_badges.integration_badge')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cider.ciderinfrastructure')),
            ],
            options={
                'unique_together': {('resource_id', 'badge_id')},
            },
        ),
        migrations.CreateModel(
            name='Integration_Badge_Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_no', models.IntegerField()),
                ('badge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration_badges.integration_badge')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration_badges.integration_roadmap_task')),
            ],
            options={
                'unique_together': {('badge_id', 'task_id')},
            },
        ),
        migrations.CreateModel(
            name='Integration_Badge_Prerequisite_Badge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_no', models.IntegerField()),
                ('badge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration_badges.integration_roadmap')),
                ('prerequisite_badge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration_badges.integration_badge')),
            ],
            options={
                'unique_together': {('badge_id', 'prerequisite_badge_id')},
            },
        ),
    ]
