# Generated by Django 5.0.14 on 2025-04-28 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_badge_task_workflow',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resource_badge_workflow',
            name='status',
            field=models.CharField(choices=[('not-planned', 'Not Planned'), ('planned', 'Planned'), ('tasks-completed', 'Tasks Completed'), ('verification-failed', 'Verification Failed'), ('verified', 'Verified'), ('deprecated', 'Depredated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resource_badge_workflow',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
