# Generated by Django 4.1.13 on 2024-07-03 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration_badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration_badge_prerequisite_badge',
            name='badge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_prerequisites', to='integration_badges.integration_badge'),
        ),
        migrations.AlterField(
            model_name='integration_badge_prerequisite_badge',
            name='prerequisite_badge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_required_by', to='integration_badges.integration_badge'),
        ),
    ]
