# Generated by Django 5.2.9 on 2026-01-15 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_badges', '0003_alter_resource_badge_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge_task',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_badges', to='integration_badges.task'),
        ),
        migrations.AlterField(
            model_name='resource_badge_task_workflow',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('not-completed', 'Not Completed'), ('action-needed', 'Action Needed'), ('not-applicable', 'Not Applicable')], max_length=20),
        ),
    ]
