# Generated by Django 5.2.17 on 2026-08-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_badges', '0004_alter_badge_task_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_badge_workflow',
            name='status',
            field=models.CharField(choices=[('not-planned', 'Not Planned'), ('planned', 'Planned'), ('tasks-completed', 'Tasks Completed'), ('verification-failed', 'Verification Failed'), ('verified', 'Verified'), ('deprecated', 'Depredated'), ('exemption-requested', 'Exemption Requested'), ('exempted', 'Exempted'), ('exemption-rejected', 'Exemption Rejected')], max_length=20),
        ),
    ]
