# Generated by Django 4.1.13 on 2024-09-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_badges', '0004_integration_workflow_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration_badge',
            name='default_badge_access_url_label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='integration_resource_badge',
            name='badge_access_url_label',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='integration_roadmap_task',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='integration_workflow',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
