# Generated by Django 4.1.13 on 2024-09-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration_badges', '0005_alter_integration_badge_default_badge_access_url_label_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Integration_Roadmap_Task',
            new_name='Integration_Task',
        ),
    ]
