# Generated by Django 4.1.13 on 2025-01-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cider', '0002_alter_ciderinfrastructure_project_affiliation'),
        ('integration_badges', '0006_rename_integration_roadmap_task_integration_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Integration_Workflow',
            new_name='Integration_Badge_Workflow',
        ),
        migrations.AlterModelOptions(
            name='integration_badge',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='integration_roadmap',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='integration_task',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Integration_Badge_Task_Workflow',
            fields=[
                ('workflow_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=20)),
                ('stateUpdatedBy', models.CharField(max_length=50)),
                ('stateUpdatedAt', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('badge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration_badges.integration_badge')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cider.ciderinfrastructure')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration_badges.integration_task')),
            ],
        ),
    ]
