# Generated by Django 4.1.13 on 2025-01-30 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration_badges', '0007_rename_integration_workflow_integration_badge_workflow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integration_badge_task_workflow',
            old_name='stateUpdatedAt',
            new_name='state_updated_at',
        ),
        migrations.RenameField(
            model_name='integration_badge_task_workflow',
            old_name='stateUpdatedBy',
            new_name='state_updated_by',
        ),
        migrations.RenameField(
            model_name='integration_badge_workflow',
            old_name='stateUpdatedAt',
            new_name='state_updated_at',
        ),
        migrations.RenameField(
            model_name='integration_badge_workflow',
            old_name='stateUpdatedBy',
            new_name='state_updated_by',
        ),
        migrations.AlterField(
            model_name='integration_badge_task',
            name='badge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_tasks', to='integration_badges.integration_badge'),
        ),
    ]
