# Generated by Django 5.0.12 on 2025-02-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_badges', '0008_rename_stateupdatedat_integration_badge_task_workflow_state_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration_badge_workflow',
            name='state',
            field=models.CharField(choices=[('not-planned', 'Not Planned'), ('planned', 'Planned'), ('task-completed', 'Task Completed'), ('verification-failed', 'Verification Failed'), ('verified', 'Verified'), ('deprecated', 'Deprecated')], max_length=20),
        ),
    ]
