# Generated by Django 5.0.12 on 2025-02-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_badges', '0009_alter_integration_badge_workflow_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration_badge_task_workflow',
            name='state',
            field=models.CharField(choices=[('complete', 'Complete'), ('not-complete', 'Not Complete')], max_length=20),
        ),
    ]
