# Generated by Django 5.0.12 on 2025-02-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_badges', '0010_alter_integration_badge_task_workflow_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration_badge_task_workflow',
            name='state',
            field=models.CharField(choices=[('completed', 'Completed'), ('not-completed', 'Not Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='integration_badge_workflow',
            name='state',
            field=models.CharField(choices=[('not-planned', 'Not Planned'), ('planned', 'Planned'), ('task-completed', 'Task Completed'), ('verification-failed', 'Verification Failed'), ('verified', 'Verified'), ('deprecated', 'Depredated')], max_length=20),
        ),
    ]
