# Generated by Django 5.0.12 on 2025-02-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_badges', '0011_alter_integration_badge_task_workflow_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration_badge_task',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='integration_roadmap_badge',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
