# Generated by Django 5.0.12 on 2025-02-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration_badges', '0012_integration_badge_task_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integration_badge_task_workflow',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='integration_badge_task_workflow',
            old_name='state_updated_at',
            new_name='status_updated_at',
        ),
        migrations.RenameField(
            model_name='integration_badge_task_workflow',
            old_name='state_updated_by',
            new_name='status_updated_by',
        ),
        migrations.RenameField(
            model_name='integration_badge_workflow',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='integration_badge_workflow',
            old_name='state_updated_at',
            new_name='status_updated_at',
        ),
        migrations.RenameField(
            model_name='integration_badge_workflow',
            old_name='state_updated_by',
            new_name='status_updated_by',
        ),
    ]
