# Generated by Django 5.0.12 on 2025-03-01 03:22

import integration_badges.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_badges', '0013_rename_state_integration_badge_task_workflow_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseFile',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100, null=True)),
                ('file_data', models.BinaryField(editable=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='integration_badge',
            name='graphic',
            field=models.ImageField(null=True, storage=integration_badges.models.DatabaseFileStorage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='integration_roadmap',
            name='graphic',
            field=models.ImageField(null=True, storage=integration_badges.models.DatabaseFileStorage, upload_to=''),
        ),
    ]
