# Generated by Django 5.0.12 on 2025-03-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_badges', '0014_databasefile_alter_integration_badge_graphic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasefile',
            name='content_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
