# Generated by Django 5.0.14 on 2025-04-11 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cider', '0005_ciderinfrastructure_protected_attributes_and_more'),
        ('integration_badges', '0015_databasefile_content_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integration_resource_badge',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='integration_badge_task_workflow',
            name='info_resourceid',
            field=models.CharField(default='DEFAULT', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integration_badge_task_workflow',
            name='roadmap_id',
            field=models.ForeignKey(default=67, on_delete=django.db.models.deletion.CASCADE, to='integration_badges.integration_roadmap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integration_badge_workflow',
            name='info_resourceid',
            field=models.CharField(default='DEFAULT', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integration_badge_workflow',
            name='roadmap_id',
            field=models.ForeignKey(default=67, on_delete=django.db.models.deletion.CASCADE, related_name='badge_workflow_resource_set', related_query_name='badge_workflow_resource_ref', to='integration_badges.integration_roadmap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integration_resource_badge',
            name='info_resourceid',
            field=models.CharField(default='DEFAULT', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integration_resource_badge',
            name='roadmap_id',
            field=models.ForeignKey(default=67, on_delete=django.db.models.deletion.CASCADE, to='integration_badges.integration_roadmap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integration_resource_roadmap',
            name='info_resourceid',
            field=models.CharField(default='DEFAULT', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integration_badge',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='integration_resource_badge',
            name='resource_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cider.ciderinfrastructure'),
        ),
        migrations.AlterField(
            model_name='integration_roadmap',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='integration_task',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='integration_resource_badge',
            unique_together={('resource_id', 'roadmap_id', 'badge_id')},
        ),
    ]
