# Generated by Django 5.0.14 on 2025-04-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration_badges', '0016_model0411step1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration_badge_task_workflow',
            name='resource_id',
        ),
        migrations.RemoveField(
            model_name='integration_badge_workflow',
            name='resource_id',
        ),
        migrations.AlterUniqueTogether(
            name='integration_resource_badge',
            unique_together={('info_resourceid', 'roadmap_id', 'badge_id')},
        ),
        migrations.AlterUniqueTogether(
            name='integration_resource_roadmap',
            unique_together={('info_resourceid', 'roadmap_id')},
        ),
        migrations.RemoveField(
            model_name='integration_resource_badge',
            name='resource_id',
        ),
        migrations.RemoveField(
            model_name='integration_resource_roadmap',
            name='resource_id',
        ),
    ]
