FROM python:3.11-slim

ARG PWD

ENV APP_CONFIG=/app/tests/django_test_mgmt.conf
ENV PYTHONUNBUFFERED=1
WORKDIR /app

# System dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install pytest pytest-django pytest-mock pytest-cov

# Copy project
COPY .. .

# Entrypoint
COPY ./entrypoint-test.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
