# Generated by Django 4.1.5 on 2023-09-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('resource_v3', '0001_initial'), ('resource_v3', '0002_delete_resourcev3_delete_resourcev3catalog_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
