# Generated by Django 4.1.5 on 2023-01-26 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('URN', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=120)),
                ('Content', models.CharField(max_length=8000)),
                ('NewsStart', models.DateTimeField()),
                ('NewsEnd', models.DateTimeField(blank=True, null=True)),
                ('NewsType', models.CharField(max_length=32)),
                ('DistributionOptions', models.CharField(blank=True, max_length=120, null=True)),
                ('WebURL', models.CharField(max_length=320, null=True)),
                ('Affiliation', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='News_Publisher',
            fields=[
                ('OrganizationID', models.IntegerField(primary_key=True, serialize=False)),
                ('OrganizationName', models.CharField(max_length=300)),
                ('NewsURNPrefix', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='News_Associations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssociatedType', models.CharField(max_length=16)),
                ('AssociatedID', models.CharField(db_index=True, max_length=128)),
                ('NewsItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='news.news')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='Publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspublisher', to='news.news_publisher'),
        ),
    ]
