# Generated by Django 4.1.5 on 2023-02-14 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_associations',
            name='NewsItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Associations', to='news.news'),
        ),
    ]
