# Generated by Django 4.1.5 on 2023-09-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceV4',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Affiliation', models.CharField(max_length=32)),
                ('LocalID', models.CharField(blank=True, max_length=200, null=True)),
                ('QualityLevel', models.CharField(max_length=16, null=True)),
                ('Name', models.CharField(max_length=255)),
                ('ResourceGroup', models.CharField(max_length=64)),
                ('Type', models.CharField(max_length=64)),
                ('ShortDescription', models.CharField(blank=True, max_length=1200, null=True)),
                ('ProviderID', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.CharField(blank=True, max_length=24000, null=True)),
                ('Topics', models.CharField(blank=True, max_length=1000, null=True)),
                ('Keywords', models.CharField(blank=True, max_length=1000, null=True)),
                ('Audience', models.CharField(blank=True, max_length=200, null=True)),
                ('StartDateTime', models.DateTimeField(blank=True, null=True)),
                ('EndDateTime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceV4Catalog',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(max_length=255)),
                ('Affiliation', models.CharField(max_length=32)),
                ('ShortDescription', models.CharField(max_length=1000)),
                ('CatalogMetaURL', models.URLField(blank=True)),
                ('CatalogUserURL', models.URLField(blank=True)),
                ('CatalogAPIURL', models.CharField(blank=True, max_length=200)),
                ('CatalogSchemaURL', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceV4Local',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('Affiliation', models.CharField(db_index=True, max_length=32)),
                ('LocalID', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('LocalType', models.CharField(blank=True, max_length=32, null=True)),
                ('LocalURL', models.CharField(blank=True, max_length=200, null=True)),
                ('CatalogMetaURL', models.CharField(blank=True, max_length=200, null=True)),
                ('EntityJSON', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceV4Relation',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('FirstResourceID', models.CharField(db_index=True, max_length=200)),
                ('SecondResourceID', models.CharField(db_index=True, max_length=200)),
                ('RelationType', models.CharField(max_length=32)),
            ],
        ),
    ]
