# Generated by Django 4.1.11 on 2023-10-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_v4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcev4local',
            name='LocalURL',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
